default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  prepared_statements: false

development:
  <<: *default

test:
  <<: *default

production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    url: <%= ENV['CABLE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
